### ISSUE TITLE
clean resources

### ISSUE THREAD

**Issue by BenjaminLetz** [wurmf/OpenBooth#1]
In den Resources sind einige unnötige Dateien (Bilder, etc.), es werden verschiedene Buttons für den selben Zweck verwendet.
Das muss alles vereinheitlicht werden.

@m.schrer commented a month ago  

Unbenutzte Icons sind entfernt. Zu überprüfen sind noch mögliche unnötige doppelte Ausführungen von einzelnen Icons, außerdem die GreenScreen Hintergründe die derzeit noch im H2EmbeddedHandler und im GreenScreen-Code selbst referenziert werden.

**Comment by schrer** [comment]
Resources are cleaned for now. Any double-defined images will be deleted after Milestone 1.0, together with bigger changes on the GUI
