### ISSUE TITLE
Triggering Photo in filter selection

### ISSUE THREAD

**Issue by BenjaminLetz** [wurmf/OpenBooth#27]
Triggering a Photo in the filter selection does not work

**Comment by schrer** [comment]
Problem could be caused by the ScrollPane, that probably catches any keystroke if it is selected.
So a fix would probably be to replace the ScrollPane with something else that does not have such behavior.

**Comment by schrer** [comment]
Found a way to remove the scroll-bars of the ScrollPane without removing the ScrollPane entirely. Triggering works now in all cases.
FIXED
