### ISSUE TITLE
Kamera Auslösen von allen Seiten

### ISSUE THREAD

**Issue by BenjaminLetz** [wurmf/OpenBooth#3]
Ist: Auslösen ist nur auf der Hauptseite möglich (NumTaste 1 für Kamera 1, ...), dadurch kann z.B. kein Foto geschossen werden wenn man den Preview im Vordergrund hat.

Soll: Auslösen soll auf allen Seiten möglich werden, nach gleichem Schema wie auf Hauptseite (NumTasten)

**Comment by wurmf** [comment]
Triggering works for all views and pages except for the shot view

**Comment by wurmf** [comment]
Update: Triggering from filter selection window does not work

**Comment by schrer** [comment]
Triggering works in all Frames the Customer can access.
Only in the frame for filter selection there is a bug that sometimes prevents the user from triggering.
This bug has its own issue #27
Therefore closing this issue.
