### ISSUE TITLE
implement a webserver for images

### ISSUE THREAD

**Issue by wurmf** [wurmf/OpenBooth#42]
In order to be able to let many people view the images at the same time and to download them it is necessary to implement a webserver, where all images are stored and can be accessed through a web application

**Comment by schrer** [comment]
Implementing the server would probably be overkill. It would be better to use an existing application that can do this and write an integration for our application.
A first candidate would be [Lychee (Github site)](https://github.com/LycheeOrg/Lychee), which seems to satisfy our prerequisites.
Testing of Lychee will follow in the next few days.

**Comment by schrer** [comment]
Lychee will be the service used to upload images, this issue is no longer active and is replaced by Issue #59
