### ISSUE TITLE
Implement password in configuration persistence

### ISSUE THREAD

**Issue by schrer** [wurmf/OpenBooth#50]
Having (possibly multiple) admin users is useless, it would be better to have just one password and no username, that will be set at first startup and can still be changed later on.

**Comment by wurmf** [comment]
Because the whole persistence layer was changed to use config files as a key-value store instead of an extensive database, the login has to be reimplemented

**Comment by wurmf** [comment]
This is no urgent issue, because a login has no real use at the moment. If no touchscreen is used, then the user cannot close the running application without a mouse in full screen mode.
