### ISSUE TITLE
Neue Bilder in Ansichten eintragen

### ISSUE THREAD

**Issue by BenjaminLetz** [wurmf/OpenBooth#6]
Neue Bilder müssen in die Vollbildansicht und die Bild-Übersicht eingetragen werden.
Es muss kontrolliert werden inwieweit das bereits funktioniert und wo noch nachgebessert werden muss.

In der Vollbildansicht verschwinden Teilweise die Pfeil-Buttons zum wechseln auf das nächste/vorherige Bild. Dieser Fehler muss auch überprüft werden.

**Comment by wurmf** [comment]
Duplicate of #18 - closed
